version: '3.8'

services:
  backend:
    build: ./backend
    container_name: brainboost
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data 
    environment:
      - DATABASE_URL=sqlite:///./test.db  # Caminho do banco SQLite
    restart: always
    env_file:
      - .env

  # frontend: 
  #   build: ./frontend